In [93]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [94]:
data = pd.read_csv('ev_data.csv')

In [95]:
data.head()

,brand,model,top_speed_kmh,battery_capacity_kWh,battery_type,number_of_cells,torque_nm,efficiency_wh_per_km,range_km,acceleration_0_100_s,...,towing_capacity_kg,cargo_volume_l,seats,drivetrain,segment,length_mm,width_mm,height_mm,car_body_type,source_url
0,Abarth,500e Convertible,155,37.8,Lithium-ion,192.0,235.0,156,225,7.0,...,0.0,185,4,FWD,B - Compact,3673,1683,1518,Hatchback,https://ev-database.org/car/1904/Abarth-500e-Convertible
1,Abarth,500e Hatchback,155,37.8,Lithium-ion,192.0,235.0,149,225,7.0,...,0.0,185,4,FWD,B - Compact,3673,1683,1518,Hatchback,https://ev-database.org/car/1903/Abarth-500e-Hatchback
2,Abarth,600e Scorpionissima,200,50.8,Lithium-ion,102.0,345.0,158,280,5.9,...,0.0,360,5,FWD,JB - Compact,4187,1779,1557,SUV,https://ev-database.org/car/3057/Abarth-600e-Scorpionissima
3,Abarth,600e Turismo,200,50.8,Lithium-ion,102.0,345.0,158,280,6.2,...,0.0,360,5,FWD,JB - Compact,4187,1779,1557,SUV,https://ev-database.org/car/3056/Abarth-600e-Turismo
4,Aiways,U5,150,60.0,Lithium-ion,NaN,310.0,156,315,7.5,...,NaN,496,5,FWD,JC - Medium,4680,1865,1700,SUV,https://ev-database.org/car/1678/Aiways-U5

In [96]:
data = data.drop(columns='source_url')

In [97]:
data.columns

Index(['brand', 'model', 'top_speed_kmh', 'battery_capacity_kWh',
       'battery_type', 'number_of_cells', 'torque_nm', 'efficiency_wh_per_km',
       'range_km', 'acceleration_0_100_s', 'fast_charging_power_kw_dc',
       'fast_charge_port', 'towing_capacity_kg', 'cargo_volume_l', 'seats',
       'drivetrain', 'segment', 'length_mm', 'width_mm', 'height_mm',
       'car_body_type'],
      dtype='object')

In [98]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 478 entries, 0 to 477
Data columns (total 21 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   brand                      478 non-null    object
 1   model                      477 non-null    object
 2   top_speed_kmh              478 non-null    int64
 3   battery_capacity_kWh       478 non-null    float64
 4   battery_type               478 non-null    object
 5   number_of_cells            276 non-null    float64
 6   torque_nm                  471 non-null    float64
 7   efficiency_wh_per_km       478 non-null    int64
 8   range_km                   478 non-null    int64
 9   acceleration_0_100_s       478 non-null    float64
 10  fast_charging_power_kw_dc  477 non-null    float64
 11  fast_charge_port           477 non-null    object
 12  towing_capacity_kg         452 non-null    float64
 13  cargo_volume_l             477 non-null    object
 14  seats                      478 non-null    int64
 15  drivetrain                 478 non-null    object
 16  segment                    478 non-null    object
 17  length_mm                  478 non-null    int64
 18  width_mm                   478 non-null    int64
 19  height_mm                  478 non-null    int64
 20  car_body_type              478 non-null    object
dtypes: float64(6), int64(7), object(8)
memory usage: 78.6+ KB

In [99]:
data.shape

(478, 21)

In [100]:
data.isnull().sum()

brand                          0
model                          1
top_speed_kmh                  0
battery_capacity_kWh           0
battery_type                   0
number_of_cells              202
torque_nm                      7
efficiency_wh_per_km           0
range_km                       0
acceleration_0_100_s           0
fast_charging_power_kw_dc      1
fast_charge_port               1
towing_capacity_kg            26
cargo_volume_l                 1
seats                          0
drivetrain                     0
segment                        0
length_mm                      0
width_mm                       0
height_mm                      0
car_body_type                  0
dtype: int64

In [101]:
data['number_of_cells'] = data['number_of_cells'].fillna(data['number_of_cells'].mean())

In [102]:
data = data.dropna()

In [103]:
data.shape

(442, 21)

In [104]:
data.isnull().sum()

brand                        0
model                        0
top_speed_kmh                0
battery_capacity_kWh         0
battery_type                 0
number_of_cells              0
torque_nm                    0
efficiency_wh_per_km         0
range_km                     0
acceleration_0_100_s         0
fast_charging_power_kw_dc    0
fast_charge_port             0
towing_capacity_kg           0
cargo_volume_l               0
seats                        0
drivetrain                   0
segment                      0
length_mm                    0
width_mm                     0
height_mm                    0
car_body_type                0
dtype: int64

In [105]:
data.head()

,brand,model,top_speed_kmh,battery_capacity_kWh,battery_type,number_of_cells,torque_nm,efficiency_wh_per_km,range_km,acceleration_0_100_s,...,fast_charge_port,towing_capacity_kg,cargo_volume_l,seats,drivetrain,segment,length_mm,width_mm,height_mm,car_body_type
0,Abarth,500e Convertible,155,37.8,Lithium-ion,192.0,235.0,156,225,7.0,...,CCS,0.0,185,4,FWD,B - Compact,3673,1683,1518,Hatchback
1,Abarth,500e Hatchback,155,37.8,Lithium-ion,192.0,235.0,149,225,7.0,...,CCS,0.0,185,4,FWD,B - Compact,3673,1683,1518,Hatchback
2,Abarth,600e Scorpionissima,200,50.8,Lithium-ion,102.0,345.0,158,280,5.9,...,CCS,0.0,360,5,FWD,JB - Compact,4187,1779,1557,SUV
3,Abarth,600e Turismo,200,50.8,Lithium-ion,102.0,345.0,158,280,6.2,...,CCS,0.0,360,5,FWD,JB - Compact,4187,1779,1557,SUV
6,Alfa,Romeo Junior Elettrica 54 kWh,150,50.8,Lithium-ion,102.0,260.0,128,320,9.0,...,CCS,0.0,400,5,FWD,JB - Compact,4173,1781,1532,SUV

In [106]:
data['brand'].value_counts()

brand
Mercedes-Benz    42
Audi             28
Porsche          26
Volkswagen       23
Ford             21
BMW              20
Volvo            18
Smart            17
BYD              16
Peugeot          15
Opel             14
Hyundai          12
Kia              12
Citroen          12
Skoda            12
NIO              12
MG               10
Renault          10
Zeekr             9
Polestar          9
XPENG             9
Fiat              8
Mini              8
Toyota            7
Tesla             7
GWM               6
Lotus             6
Nissan            5
DS                5
CUPRA             5
Genesis           4
Abarth            4
Lexus             3
Hongqi            3
Alfa              2
Alpine            2
Dacia             2
VinFast           2
Mazda             2
Jeep              2
Jaguar            1
Honda             1
Cadillac          1
Lynk&Co           1
Maserati          1
Maxus             1
Lucid             1
KGM               1
Leapmotor         1
Lancia            1
Subaru            1
Voyah             1
Name: count, dtype: int64

In [107]:
data['model'].value_counts()

model
X Privilege AWD (MY25)             1
500e Convertible                   1
500e Hatchback                     1
600e Scorpionissima                1
600e Turismo                       1
                                  ..
Q4 Sportback e-tron 40             1
A6 Sportback e-tron quattro        1
A6 Sportback e-tron performance    1
A6 Sportback e-tron                1
A6 Avant e-tron quattro            1
Name: count, Length: 442, dtype: int64

In [108]:
data['battery_type'].value_counts()

battery_type
Lithium-ion    442
Name: count, dtype: int64

In [109]:
data = data.drop(columns='battery_type')

In [110]:
data['fast_charge_port'].value_counts()

fast_charge_port
CCS        441
CHAdeMO      1
Name: count, dtype: int64

In [111]:
data = data.drop(columns='fast_charge_port')

In [112]:
data['drivetrain'].value_counts()

drivetrain
AWD    178
FWD    136
RWD    128
Name: count, dtype: int64

In [113]:
data['segment'].value_counts()

segment
JC - Medium          86
JD - Large           53
N - Passenger Van    46
JB - Compact         44
F - Luxury           44
E - Executive        30
D - Large            28
JE - Executive       28
JF - Luxury          28
C - Medium           28
B - Compact          25
A - Mini              2
Name: count, dtype: int64

In [114]:
data['car_body_type'].value_counts()

car_body_type
SUV                    230
Sedan                   58
Hatchback               49
Small Passenger Van     46
Liftback Sedan          31
Station/Estate          26
Cabriolet                2
Name: count, dtype: int64

In [115]:
data.shape

(442, 19)

One-Hot Encode : car_body_type, segment, drivetrain

In [116]:
data = pd.get_dummies(data, columns=['car_body_type', 'segment', 'drivetrain'], drop_first=True)

In [117]:
data

,brand,model,top_speed_kmh,battery_capacity_kWh,number_of_cells,torque_nm,efficiency_wh_per_km,range_km,acceleration_0_100_s,fast_charging_power_kw_dc,...,segment_E - Executive,segment_F - Luxury,segment_JB - Compact,segment_JC - Medium,segment_JD - Large,segment_JE - Executive,segment_JF - Luxury,segment_N - Passenger Van,drivetrain_FWD,drivetrain_RWD
0,Abarth,500e Convertible,155,37.8,192.000000,235.0,156,225,7.0,67.0,...,False,False,False,False,False,False,False,False,True,False
1,Abarth,500e Hatchback,155,37.8,192.000000,235.0,149,225,7.0,67.0,...,False,False,False,False,False,False,False,False,True,False
2,Abarth,600e Scorpionissima,200,50.8,102.000000,345.0,158,280,5.9,79.0,...,False,False,True,False,False,False,False,False,True,False
3,Abarth,600e Turismo,200,50.8,102.000000,345.0,158,280,6.2,79.0,...,False,False,True,False,False,False,False,False,True,False
6,Alfa,Romeo Junior Elettrica 54 kWh,150,50.8,102.000000,260.0,128,320,9.0,85.0,...,False,False,True,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
472,Zeekr,7X Performance AWD,210,94.0,485.293478,710.0,173,450,3.8,260.0,...,False,False,False,False,True,False,False,False,False,False
473,Zeekr,7X Premium RWD,210,71.0,485.293478,440.0,148,365,6.0,240.0,...,False,False,False,False,True,False,False,False,False,True
474,Zeekr,X Core RWD (MY25),190,49.0,485.293478,343.0,148,265,5.9,70.0,...,False,False,True,False,False,False,False,False,False,True
475,Zeekr,X Long Range RWD (MY25),190,65.0,485.293478,343.0,146,360,5.6,114.0,...,False,False,True,False,False,False,False,False,False,True
476,Zeekr,X Privilege AWD (MY25),190,65.0,485.293478,543.0,153,350,3.8,114.0,...,False,False,True,False,False,False,False,False,False,False

In [118]:
data = data.drop(columns='model')

In [119]:
data['cargo_volume_l'] = pd.to_numeric(data['cargo_volume_l'], errors='coerce')
data['cargo_volume_l'] = data['cargo_volume_l'].fillna(data['cargo_volume_l'].median())

Target Encoder for Brands

In [120]:
!pip install category_encoders
from category_encoders import TargetEncoder

Requirement already satisfied: category_encoders in /usr/local/lib/python3.12/dist-packages (2.9.0)
Requirement already satisfied: numpy>=1.14.0 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (2.0.2)
Requirement already satisfied: pandas>=1.0.5 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (2.2.2)
Requirement already satisfied: patsy>=0.5.1 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (1.0.2)
Requirement already satisfied: scikit-learn>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (1.6.1)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (1.16.3)
Requirement already satisfied: statsmodels>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (0.14.6)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.5->category_encoders) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.5->category_encoders) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.5->category_encoders) (2026.1)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.6.0->category_encoders) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.6.0->category_encoders) (3.6.0)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.12/dist-packages (from statsmodels>=0.9.0->category_encoders) (26.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.0.5->category_encoders) (1.17.0)

In [121]:
X = data.drop(columns=['range_km', 'brand'])
y = data['range_km']

In [122]:
te = TargetEncoder(cols=['brand'], smoothing=10)
X['brand'] = te.fit_transform(data['brand'], y)

In [123]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

Random Forest

In [124]:
from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(n_estimators=100, random_state=42)
rf.fit(X_train, y_train)

RandomForestRegressor(random_state=42)

XGBoost

In [125]:
from xgboost import XGBRegressor

xgb = XGBRegressor(n_estimators=100, random_state=42)
xgb.fit(X_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=None, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=100,
             n_jobs=None, num_parallel_tree=None, ...)

Comparison

In [126]:
from sklearn.metrics import mean_absolute_error, r2_score

for name, model in [('Random Forest', rf), ('XGBoost', xgb)]:
    preds = model.predict(X_test)
    print(f"{name}")
    print(f"  MAE : {mean_absolute_error(y_test, preds):.2f} km")
    print(f"  R²  : {r2_score(y_test, preds):.4f}")
    print()

Random Forest
  MAE : 11.90 km
  R²  : 0.9733

XGBoost
  MAE : 12.31 km
  R²  : 0.9750

In [127]:
import joblib

joblib.dump(rf, 'random_forest_model.pkl')
joblib.dump(X_train.columns.tolist(), 'columns.pkl')
joblib.dump(te, 'target_encoder.pkl')

['target_encoder.pkl']